Added support for push notifications for published pages
IMGIITRoorkee/omniport-app-student-profile pull request #11
Opened 2020-11-27 07:37 UTC by weastel

Signed-off-by: Drumil Patel <drumilpatel720@gmail.com>

2020-11-27 09:18 UTC, algomaster99 requested changes

2020-11-27 09:18 UTC, algomaster99 commented on tasks/publish_page.py
> +from http import HTTPStatus
Should be just below `requests`.

2020-11-27 09:18 UTC, algomaster99 commented on tasks/publish_page.py
> +from student_profile.utils.send_published_page_notifications import (
Change file name to `student_profile.utils.send_published_page_notification`.

2020-11-27 09:18 UTC, algomaster99 commented on tasks/publish_page.py
> +    :parma person: Person who have requested for published page.
Person who **has**.

2020-11-27 09:18 UTC, algomaster99 commented on tasks/publish_page.py
> +        resp = requests.post(
Change the variable to `publish_request`.

2020-11-27 09:18 UTC, algomaster99 commented on tasks/publish_page.py
> +            enrolment_no,
Either add a trailing coma or don't but be consistent. Rest all of the code does not have it so maybe remove it from here as well.

2020-11-27 09:18 UTC, algomaster99 commented on tasks/publish_page.py
> +    if resp.status_code == HTTPStatus.CREATED:
What are the other possible response codes that can be retrieved from your service?

2020-11-27 09:18 UTC, algomaster99 commented on utils/send_published_page_notifications.py
> +from categories.models import Category
Would be just below - `from notifications.actions import push_notification`.

2020-11-27 09:18 UTC, algomaster99 commented on utils/send_published_page_notifications.py
> +    :param person:
Complete the docstrings.

2020-11-27 09:18 UTC, algomaster99 commented on utils/send_published_page_notifications.py
> +        template=f'Your page on "https://students.iitr.ac.in/{enrolment_no}.html" has been published.',
`f'Your page on \'https://students.iitr.ac.in/{enrolment_no}.html\' has been published.'`

I think storing this in `base.yml` will make more sense. Don't just hardcode it here.

2020-11-27 09:18 UTC, algomaster99 commented on utils/send_published_page_notifications.py
> +        web_onclick_url='',
We should redirect the users to the published page on click, right?

2020-11-28 16:52 UTC, weastel commented on tasks/publish_page.py
> +    if resp.status_code == HTTPStatus.CREATED:
Just 500 internal server can be another possible error
And It will can be due to just our error. So possibility of 500 is kind of a fault.

2020-11-28 17:19 UTC, algomaster99 approved these changes

2020-11-28 17:39 UTC, merged