Modify PreviousEducation's serializer to handle is_percentage boolean
IMGIITRoorkee/omniport-app-student-profile pull request #4
Opened 2020-10-02 18:44 UTC by nisarg73

2020-10-05 13:27 UTC, shreyansh23 commented on serializers/generic_serializers.py
> +                if percentage is None:
@nisarg73 While create operation - if percentage is not `None` then `validated_date.is_percentage` should be set as True. I cannot see that happening here.

2020-10-05 13:32 UTC, shreyansh23 commented
@nisarg73 Could you please mention the bug which this PR is trying to resolve.

2020-10-05 14:27 UTC, nisarg73 commented on serializers/generic_serializers.py
> +                if percentage is None:
But what if both CGPA and Percentage are specified and `Consider priority of percentage greater than CGPA` is set as `false`?

2020-10-05 14:32 UTC, nisarg73 commented
@shreyansh23 I forgot to open an issue for this. The bug is that currently `PreviousEducation` is defined such that if `percentage` is specified then it will by default have greater priority over CGPA.

By if is so won't this boolean of `Consider priority of percentage greater than CGPA` pretty much non-existent?

![Screenshot_2020-10-05 SHP](https://user-images.githubusercontent.com/25002246/95092611-7743c500-0745-11eb-8ec1-23c258136898.png)

Hence this PR was to check this boolean first and then correspondingly set `is_percentage`

2020-10-05 16:52 UTC, nisarg73 commented on serializers/generic_serializers.py
> +                if percentage is None:
No actually. :neutral_face: 

I mean `cgpa` and `percentage` are not required fields. Which makes sense, for cases where one doesn't want to explicitly state their past grades. So `is_percentage` will only depend on whether or not `percentage` is `None` or not. Which I have already implemented.

You can check this logic on your local by pulling this branch and https://github.com/IMGIITRoorkee/omniport-frontend-student-profile/pull/11

2020-10-06 03:26 UTC, pradumangoyal commented on serializers/generic_serializers.py
> +                if percentage is None:
No, they are not required fields as we can't make any of them required as we have to offer a choice in between them. And if you are adding a past record of your education, you should state your performance, otherwise, it won't make much sense to mention that.

2020-10-09 15:19 UTC, shreyansh23 requested changes

2020-10-09 15:19 UTC, shreyansh23 commented on serializers/generic_serializers.py
>                  is_percentage = validated_data.get('is_percentage', False)
@nisarg73 In update method modify the optional parameter in `.get`. Like `is_percentage = validated_data.get('is_percentage', instance.is_percentage)` same for cgpa and percentage also.

2020-10-09 15:19 UTC, shreyansh23 commented on serializers/generic_serializers.py
> +                elif cgpa and percentage is not None:
@nisarg73 `cgpa and percentage is not None` and `cgpa is not None and percentage is not None` both will work but please use the latter one for consistency.

2020-10-09 15:19 UTC, shreyansh23 commented on serializers/generic_serializers.py
> +                elif cgpa and percentage is not None:
Here also

2020-10-09 15:34 UTC, shreyansh23 approved these changes

2020-10-09 15:43 UTC, merged