Add queue and worker for shp publish
IMGIITRoorkee/omniport-app-student-profile pull request #5
Opened 2020-11-11 22:22 UTC by weastel

Signed-off-by: Drumil Patel <drumilpatel720@gmail.com>

2020-11-12 04:18 UTC, algomaster99 requested changes

2020-11-12 04:18 UTC, algomaster99 commented on tasks/publish_page.py
> +
Delete newline

2020-11-12 04:18 UTC, algomaster99 commented on tasks/publish_page.py
> +SHP = CONFIGURATION.integrations.get('SHP')
Configure this integration something similar to [this](https://github.com/IMGIITRoorkee/omniport-app-faculty-profile/blob/master/views.py#L282).
You can use the `get` view to detect if the configuration exists and if it does not, you can hide the button for publishing on fronted.

Pass this configuration from the view.

2020-11-12 04:18 UTC, algomaster99 commented on views.py
> +                "message": "Successfully added to publish queue"
Use `''`

2020-11-12 04:18 UTC, algomaster99 commented on tasks/__init__.py
> +from student_profile.tasks.publish_page import publish_page
Add a newline in this file

2020-11-13 03:37 UTC, algomaster99 requested changes

2020-11-13 03:37 UTC, algomaster99 commented on tasks/publish_page.py
> +    :return: Publishes page with given enrollment_no
Write about params too
```
:param full_name: Full name of the student
...
```

2020-11-13 03:37 UTC, algomaster99 commented on views.py
> +class PublishPageView(APIView):
```python
from django.core.exceptions import ImproperlyConfigured

class PublishPageView(APIView):
    """
    API endpoint to publish a preview page
    """

    permission_classes = (get_has_role('Student'), )
    SHP = CONFIGURATION.integrations.get('shp', False)

    def check_configuration():
        if self.SHP:
            attributes = [
                self.SHP.get('shp_publish_endpoint')
            ]
            if all(attributes):
                return True
            else:
                raise ImproperlyConfigured
        else:
            return False

    def get(self, request):
        """
        Returns whether SHP configuration exists or not
        :return: whether SHP configuration exists or not
        """

        try:
            is_configured = self.check_configuration()
            if is_configured:
                return Response(
                    'SHP configuration detected',
                    status=status.HTTP_200_OK,
                )
            return Response(
                'You probably do not need students page published',
                status=status.HTTP_404_NOT_FOUND,
            )
        except ImproperlyConfigured:
            return Response(
                (
                    'SHP falsely configured. Please provide `shp_publish_endpoint` '
                    'in the configuration'
                ),
                status=status.HTTP_406_NOT_ACCEPTABLE,
            )

    def post(self, request):
        try:
            is_configured = self.check_configuration()
        except ImproperlyConfigured:
            return Response(
                (
                    'SHP falsely configured. Please provide `shp_publish_endpoint` '
                    'in the configuration'
                ),
                status=status.HTTP_406_NOT_ACCEPTABLE,
            )
        if is_configured:
            data = request.data
            enrollment_no = data['enrollment_no']
            full_name = data['full_name']
            shp_endpoint = self.SHP.get('shp_publish_endpoint')

            publish_page.delay(full_name, enrollment_no, shp_endpoint)
            return Response(
                "Successfully added to publish queue",
                status=status.HTTP_200_OK, 
            )
        else:
            return Response(
                'You probably do not need students page published',
                status=status.HTTP_405_METHOD_NOT_ALLOWED,
            )
```
Would be a better way to write this.

2020-11-13 17:29 UTC, algomaster99 commented on tasks/publish_page.py
> +    except:
What are the possible errors? It is better to list them out so that it is easier to debug later.

2020-11-13 17:29 UTC, algomaster99 commented on tasks/publish_page.py
> +        pass
We should instead throw an error instead of ignoring the error.

2020-11-14 08:10 UTC, algomaster99 requested changes

2020-11-14 08:10 UTC, algomaster99 commented on tasks/publish_page.py
> +    except requests.Timeout:
I think you will have to import `from requests.exceptions import Timeout ` and then catch it here.

2020-11-14 08:10 UTC, algomaster99 commented on tasks/publish_page.py
> +        raise Exception('Request unsuccessful.')
Better to `except Exception as error:` so that we know what the error is exactly.

2020-11-14 08:10 UTC, algomaster99 commented on http_urls.py
> +from student_profile.views import SocialLinkViewSet, DragAndDropView, PublishPageView, StudentSearchList
Exceeding 79 chars.

2020-11-18 05:42 UTC, algomaster99 commented
@weastel Have you made the changes?

2020-11-19 04:20 UTC, algomaster99 requested changes

2020-11-19 04:20 UTC, algomaster99 commented on http_urls.py
> +from student_profile.views import SocialLinkViewSet, DragAndDropView, \
No.
```python
from student_profile.views import (
    SocialLinkViewSet,
    DragAndDropView,
    PublishPageView,
    StudentSearchList,
)
```

2020-11-19 04:20 UTC, algomaster99 commented on tasks/publish_page.py
> +        raise Exception(f'Request unsuccessful. Error: {str(error)}')
Please leave a newline at the end

2020-11-19 04:20 UTC, algomaster99 commented on views.py
> +from django.core.exceptions import ObjectDoesNotExist, ValidationError, ImproperlyConfigured
If you followed the rule [here](https://github.com/IMGIITRoorkee/omniport-app-student-profile/pull/5/files#diff-95cbb78df50c437785afa0b82cbe7a052c443b8e39dd1fde590b485dbfc43468R5), why not here? Please be a little more observant.

2020-11-19 04:20 UTC, algomaster99 commented on views.py
> +                "Successfully added to publish queue",
`'Successfully added to publish queue'`

2020-11-19 04:21 UTC, algomaster99 commented
![Screenshot from 2020-11-19 09-50-36](https://user-images.githubusercontent.com/35191225/99620970-b0619b80-2a4c-11eb-9c59-f7a3ec306c8c.png)
I expect you to rebase branches properly.

2020-11-23 03:53 UTC, algomaster99 commented on views.py
> +            handle = data['handle']
What if `data` is not in the POST request? You will need to return a `400 Bad Request` right?

2020-11-23 19:34 UTC, algomaster99 approved these changes

2020-11-23 19:34 UTC, algomaster99 commented on tasks/publish_page.py
> +                "SHP_TOKEN": shp_publish_token,
`'SHP_TOKEN'`

2020-11-23 19:36 UTC, weastel commented on tasks/publish_page.py
> +                "SHP_TOKEN": shp_publish_token,
Done. Thanks

2020-11-23 19:37 UTC, merged