Serialize email, branch and degree details in Profile serializer
IMGIITRoorkee/omniport-app-student-profile pull request #8
Opened 2020-11-19 15:59 UTC by nisarg73

2020-11-19 16:02 UTC, nisarg73 commented
Note: Utils functions are exactly the same as in Placement and Internship. (https://github.com/IMGIITRoorkee/omniport-app-placement-and-internship/commit/cb597cdbb15807ac300f31db6b878492331ce1d1)

2020-11-20 09:28 UTC, algomaster99 requested changes

2020-11-20 09:28 UTC, algomaster99 commented on utils/get_graduation_map.py
> +        'gra': 'UG',
Import the keys from [here](https://github.com/IMGIITRoorkee/omniport-backend/blob/master/omniport/core/kernel/constants/graduations.py).

2020-11-20 09:28 UTC, algomaster99 commented on serializers/profile.py
> +            contact_info = instance.student.person.contact_information.get()
I am just asking for general knowledge. What is returned when `student.person.contact_information` queryset has two entities of `contact_information`?

2020-11-20 09:28 UTC, algomaster99 commented on utils/get_decorated_degree.py
> +        f'{int_to_roman(int(current_semester/2))} Semester)'
Why have you divided by 2? I think you mean :
```python
current_semester = 1 if student.current_semester else 2 
```

P.S. int(a/2) is equivalent to a//2 (floor division).

2020-11-20 09:28 UTC, algomaster99 commented on utils/get_int_to_roman.py
> +def int_to_roman(num):
Did you write this on your own? Or did you at least attempt to write the code before referring to resources online? Just curious.

2020-11-20 12:55 UTC, nisarg73 commented
> Note: Utils functions are exactly the same as in Placement and Internship. ([IMGIITRoorkee/omniport-app-placement-and-internship@cb597cd](https://github.com/IMGIITRoorkee/omniport-app-placement-and-internship/commit/cb597cdbb15807ac300f31db6b878492331ce1d1))

@algomaster99

2020-11-20 13:02 UTC, nisarg73 commented on serializers/profile.py
> +            contact_info = instance.student.person.contact_information.get()
I didn't know that this is possible. Can a student have more than one institute email?

Incase of multiple entities it would throw `MultipleObjectsReturned` upon `get()`

2020-11-20 13:39 UTC, algomaster99 commented
@nisarg73 
- How does `current_semester/2` make sense? For my case, it will return III semester.
- If `'gra'` can be softcoded, then why not?

Placement App isn't a source of truth anyway.

2020-11-23 03:56 UTC, algomaster99 approved these changes

2020-11-23 03:58 UTC, merged